# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20190404_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='issuu_eng',
            field=models.URLField(default='https://e.issuu.com/anonymous-embed.html?u=onelmedia&d=craig_groeschel', max_length=149),
        ),
        migrations.AlterField(
            model_name='question',
            name='pdf_link_eng',
            field=models.URLField(default='https://gls-demo-f4707.firebaseapp.com/DISCUSSIONGUIDES/DISC01/Craig_Groeschel.pdf', max_length=349),
        ),
    ]
